#!/usr/bin/env bash
set -euo pipefail
export WORKDIR=/work
export BR_DIR=$WORKDIR/buildroot
export BUILDROOT_TAG=${BUILDROOT_TAG:-2024.02.1} # Change if needed
export BOARD_DEFCONFIG=${BOARD_DEFCONFIG:-beaglebone_defconfig}
export OUTPUT_IMAGES_DIR="$BR_DIR/output/images"

cd $WORKDIR

# 1) Clone Buildroot if not present
if [ ! -d "$BR_DIR" ]; then
  echo "Cloning Buildroot into $BR_DIR..."
  git clone --depth 1 https://git.buildroot.net/buildroot $BR_DIR

  # If a specific tag is required, check it out
  if [ -n "$BUILDROOT_TAG" ]; then
    cd $BR_DIR
    echo "Checking out tag $BUILDROOT_TAG..."
    # Fetch tags and checkout the specific version
    git fetch --tags
    # Use || true to prevent script failure if checkout fails (often due to shallow clone)
    git checkout $BUILDROOT_TAG || true
    cd $WORKDIR # Return to WORKDIR
  fi
fi

# MOVE TO THE BUILDROOT ROOT DIRECTORY TO RUN 'make'
echo "Changing directory to Buildroot root: $BR_DIR"
cd $BR_DIR

# --- DEBUG STEP: Verify content and location ---
echo "--- DEBUG: Current location and contents before make ---"
pwd
# List the first 10 files/directories to verify Makefile and configs/ are present
ls -F | head -n 10
echo "--- END DEBUG ---"
# -----------------------------------------------

# 2) Select defconfig (make will automatically look in configs/)
echo "Configuring Buildroot with $BOARD_DEFCONFIG..."
make $BOARD_DEFCONFIG

# (If you want to ensure ext4 is ON, uncomment the section below)
# sed -i 's/^# BR2_TARGET_ROOTFS_EXT4 is not set/BR2_TARGET_ROOTFS_EXT4=y/' .config || true
# make olddefconfig

# 3) Build the entire system (toolchain + rootfs)
echo "Starting build with $(nproc) threads..."
make -j$(nproc)

# 4) Check for rootfs.ext4 generated by Buildroot
if [ -f "$OUTPUT_IMAGES_DIR/rootfs.ext4" ]; then
  echo "✅ Buildroot generated rootfs.ext4 -> $OUTPUT_IMAGES_DIR/rootfs.ext4"
  cp "$OUTPUT_IMAGES_DIR/rootfs.ext4" "$WORKDIR/rootfs.ext4"
  exit 0
fi

# 5) If ext4 file is missing, package manually
TARGET_DIR="$BR_DIR/output/target"
IMG="$WORKDIR/rootfs.ext4"
IMG_SIZE_MB=${IMG_SIZE_MB:-128}  # Adjust size as needed

echo "Creating ext4 image manually: $IMG (${IMG_SIZE_MB}M)"
fallocate -l ${IMG_SIZE_MB}M $IMG || dd if=/dev/zero of=$IMG bs=1M count=${IMG_SIZE_MB}

# Format ext4
sudo mkfs.ext4 -F $IMG

# Mount, copy files (requires root permissions)
tmpmnt=$(mktemp -d)
sudo mount -o loop $IMG $tmpmnt
sudo rsync -aHAX --numeric-ids --exclude=/dev/ --exclude=/proc/ --exclude=/sys/ $TARGET_DIR/ $tmpmnt/
# sync & unmount
sync
sudo umount $tmpmnt
rmdir $tmpmnt

echo "✅ Successfully created rootfs.ext4 -> $IMG"
cp $IMG $WORKDIR/rootfs.ext4
